# Clave del proyecto y organización en SonarCloud
sonar.projectKey=ServiPlus-S-A_api-atenciones
sonar.organization=serviplus-s-a

# Directorios de código fuente y de pruebas
sonar.sources=backend/atenciones,backend/config
sonar.tests=backend/tests

# Exclusiones generales de análisis
sonar.exclusions=**/migrations/**, **/tests/**, **/node_modules/**, **/.next/**

# Cobertura de pruebas para Python (ruta relativa a la raíz del repositorio)
sonar.python.coverage.reportPaths=backend/coverage.xml

# Versión de Python para un análisis más preciso
sonar.python.version=3.12
