# Generated by Django 5.0.14 on 2026-06-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "atenciones",
            "0002_rename_audit_log_created_at_idx_audit_log_created_5a7975_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="atention",
            name="created_by",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="atention",
            name="request_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="atentionconsultant",
            name="consultant_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_id",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="atention_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="jwt_subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringnote",
            name="consultant_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name="atention",
            index=models.Index(
                fields=["created_at"], name="atention_created_467b18_idx"
            ),
        ),
    ]
