# Generated by Codex on 2026-06-16

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        (
            "atenciones",
            "0003_alter_atention_created_by_alter_atention_request_id_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="atentionconsultant",
            constraint=models.UniqueConstraint(
                fields=("atention",),
                condition=Q(is_leader=True),
                name="unique_leader_per_atention",
            ),
        ),
    ]
